version: '3'

services:
  app:
    build: .
#    ports:
#      - "8080:8080"
    expose:
      - "8080"
    networks:
      - my-pet
  nginx:
    image: nginx
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my-pet

networks:
  my-pet:
    external: true